<?php

return [
    'dependencies' => [],
    'imports' => [
        'TYPO3/CMS/Core/' => [
            'path' => 'EXT:core/Resources/Public/JavaScript/',
            'exclude' => [
                'EXT:core/Resources/Public/JavaScript/Contrib/',
            ],
        ],
        'TYPO3/CMS/Core/JavaScriptHandler.js' => 'EXT:core/Resources/Public/JavaScript/JavaScriptHandler.esm.js',
        'autosize' => 'EXT:core/Resources/Public/JavaScript/Contrib/autosize.js',
        'bootstrap' => 'EXT:core/Resources/Public/JavaScript/Contrib/bootstrap.js',
        'broadcastchannel.js' => 'EXT:core/Resources/Public/JavaScript/Contrib/broadcastchannel.js',
        'codemirror' => 'EXT:core/Resources/Public/JavaScript/Contrib/codemirror.js',
        'cropperjs' => 'EXT:core/Resources/Public/JavaScript/Contrib/cropperjs.js',
        'd3-dispatch' => 'EXT:core/Resources/Public/JavaScript/Contrib/d3-dispatch.js',
        'd3-drag' => 'EXT:core/Resources/Public/JavaScript/Contrib/d3-drag.js',
        'd3-selection' => 'EXT:core/Resources/Public/JavaScript/Contrib/d3-selection.js',
        'ev-emitter' => 'EXT:core/Resources/Public/JavaScript/Contrib/ev-emitter.js',
        'flatpickr/' => 'EXT:core/Resources/Public/JavaScript/Contrib/flatpickr/',
        'imagesloaded' => 'EXT:core/Resources/Public/JavaScript/Contrib/imagesloaded.js',
        'jquery' => 'EXT:core/Resources/Public/JavaScript/Contrib/jquery.js',
        'jquery/' => 'EXT:core/Resources/Public/JavaScript/Contrib/jquery/',
        'jquery/autocomplete.js' => 'EXT:core/Resources/Public/JavaScript/Contrib/jquery.autocomplete.js',
        'jquery-ui/' => 'EXT:core/Resources/Public/JavaScript/Contrib/jquery-ui/',
        '@lit/reactive-element' => 'EXT:core/Resources/Public/JavaScript/Contrib/@lit/reactive-element/reactive-element.js',
        '@lit/reactive-element/' => 'EXT:core/Resources/Public/JavaScript/Contrib/@lit/reactive-element/',
        'lit' => 'EXT:core/Resources/Public/JavaScript/Contrib/lit/index.js',
        'lit/' => 'EXT:core/Resources/Public/JavaScript/Contrib/lit/',
        'lit-element' => 'EXT:core/Resources/Public/JavaScript/Contrib/lit-element/index.js',
        'lit-element/' => 'EXT:core/Resources/Public/JavaScript/Contrib/lit-element/',
        'lit-html' => 'EXT:core/Resources/Public/JavaScript/Contrib/lit-html/lit-html.js',
        'lit-html/' => 'EXT:core/Resources/Public/JavaScript/Contrib/lit-html/',
        'moment' => 'EXT:core/Resources/Public/JavaScript/Contrib/moment.js',
        'moment-timezone' => 'EXT:core/Resources/Public/JavaScript/Contrib/moment-timezone.js',
        'nprogress' => 'EXT:core/Resources/Public/JavaScript/Contrib/nprogress.js',
        'sortablejs' => 'EXT:core/Resources/Public/JavaScript/Contrib/sortablejs.js',
        'tablesort.dotsep.js' => 'EXT:core/Resources/Public/JavaScript/Contrib/tablesort.dotsep.js',
        'tablesort' => 'EXT:core/Resources/Public/JavaScript/Contrib/tablesort.js',
        'taboverride' => 'EXT:core/Resources/Public/JavaScript/Contrib/taboverride.js',
    ],
];
