/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */
define(["require","TYPO3/CMS/Backend/Element/ImmediateActionElement","TYPO3/CMS/Backend/ModuleMenu","TYPO3/CMS/Backend/Viewport"],(function(e,a,t,n){"use strict";describe("TYPO3/CMS/Backend/Element/ImmediateActionElement:",()=>{let c;beforeEach(()=>{c=document.createElement("div"),document.body.appendChild(c)}),afterEach(()=>{c.remove(),c=null}),it("dispatches action when created via constructor",async()=>{const t=n.Topbar.refresh,l={callback:()=>{}};spyOn(l,"callback").and.callThrough(),n.Topbar.refresh=l.callback;const o=new a.ImmediateActionElement;o.setAttribute("action","TYPO3.Backend.Topbar.refresh"),expect(l.callback).not.toHaveBeenCalled(),c.appendChild(o),await new Promise((function(a,t){e(["TYPO3/CMS/Backend/Viewport"],(function(e){a("object"!=typeof e||"default"in e?{default:e}:Object.defineProperty(e,"default",{value:e,enumerable:!1}))}),t)})),expect(l.callback).toHaveBeenCalled(),n.Topbar.refresh=t}),it("dispatches action when created via createElement",async()=>{const a=n.Topbar.refresh,t={callback:()=>{}};spyOn(t,"callback").and.callThrough(),n.Topbar.refresh=t.callback;const l=document.createElement("typo3-immediate-action");l.setAttribute("action","TYPO3.Backend.Topbar.refresh"),expect(t.callback).not.toHaveBeenCalled(),c.appendChild(l),await new Promise((function(a,t){e(["TYPO3/CMS/Backend/Viewport"],(function(e){a("object"!=typeof e||"default"in e?{default:e}:Object.defineProperty(e,"default",{value:e,enumerable:!1}))}),t)})),expect(t.callback).toHaveBeenCalled(),n.Topbar.refresh=a}),it("dispatches action when created from string",async()=>{const a=t.App.refreshMenu,n={callback:()=>{}};spyOn(n,"callback").and.callThrough(),t.App.refreshMenu=n.callback;const l=document.createRange().createContextualFragment('<typo3-immediate-action action="TYPO3.ModuleMenu.App.refreshMenu"></typo3-immediate-action>').querySelector("typo3-immediate-action");expect(n.callback).not.toHaveBeenCalled(),c.appendChild(l),await new Promise((function(a,t){e(["TYPO3/CMS/Backend/ModuleMenu"],(function(e){a("object"!=typeof e||"default"in e?{default:e}:Object.defineProperty(e,"default",{value:e,enumerable:!1}))}),t)})),expect(n.callback).toHaveBeenCalled(),t.App.refreshMenu=a}),it("dispatches action when created via innerHTML",async()=>{const a=t.App.refreshMenu,n={callback:()=>{}};spyOn(n,"callback").and.callThrough(),t.App.refreshMenu=n.callback,c.innerHTML='<typo3-immediate-action action="TYPO3.ModuleMenu.App.refreshMenu"></typo3-immediate-action>',await new Promise((function(a,t){e(["TYPO3/CMS/Backend/ModuleMenu"],(function(e){a("object"!=typeof e||"default"in e?{default:e}:Object.defineProperty(e,"default",{value:e,enumerable:!1}))}),t)})),expect(n.callback).toHaveBeenCalled(),t.App.refreshMenu=a})})}));