categories:
  felogin:
    label: 'Frontend Login'
    description: ''
    icon: actions-dice

settings:
  felogin.pid:
    default: '0'
    label: 'User Storage Page'
    type: string
    description: 'Define the Storage Folder with the Website User Records, using a comma separated list or single value'
    category: felogin
  felogin.recursive:
    default: '0'
    label: Recursive
    type: string
    enum:
      '0': '0'
      '1': '1'
      '2': '2'
      '3': '3'
      '4': '4'
      '255': '255'
    description: 'If set, also subfolder at configured recursive levels of the User Storage Page will be used'
    category: felogin
  felogin.showForgotPassword:
    default: false
    label: 'Display Password Recovery Link'
    type: bool
    description: 'If set, the section in the template to display the link to the forgot password dialogue is visible.'
    category: felogin
  felogin.showPermaLogin:
    default: false
    label: 'Display Remember Login Option'
    type: bool
    description: 'If set, the section in the template to display the option to remember the login (with a cookie) is visible.'
    category: felogin
  felogin.showLogoutFormAfterLogin:
    default: false
    label: 'Disable redirect after successful login, but display logout-form'
    type: bool
    description: 'If set, the logout form will be displayed immediately after successful login.'
    category: felogin
  felogin.emailFrom:
    default: ''
    label: 'Email Sender Address'
    type: string
    description: 'email address used as sender of the change password emails'
    category: felogin
  felogin.emailFromName:
    default: ''
    label: 'Email Sender Name'
    type: string
    description: 'Name used as sender of the change password emails'
    category: felogin
  felogin.replyToEmail:
    default: ''
    label: 'Reply-to email Address'
    type: string
    description: 'Reply-to address used in the change password emails'
    category: felogin
  felogin.dateFormat:
    default: 'Y-m-d H:i'
    label: 'Date format'
    type: string
    description: 'Format for the link is valid until message (forgot password email)'
    category: felogin
  felogin.email.layoutRootPath:
    default: ''
    label: 'Layout root path'
    type: string
    description: 'Path to layout directory used for emails'
    category: felogin
  felogin.email.templateRootPath:
    default: 'EXT:felogin/Resources/Private/Email/Templates/'
    label: 'Template root path'
    type: string
    description: 'Path to template directory used for emails'
    category: felogin
  felogin.email.partialRootPath:
    default: ''
    label: 'Partial root path'
    type: string
    description: 'Path to partial directory used for emails'
    category: felogin
  felogin.email.templateName:
    default: PasswordRecovery
    label: 'Template name for emails.'
    type: string
    description: 'HTML emails get the .html file extension, plaintext emails get the .txt file extension.'
    category: felogin
  felogin.redirectMode:
    default: ''
    label: 'Redirect Mode'
    type: string
    description: 'Comma separated list of redirect modes. Possible values: groupLogin, userLogin, login, getpost, referer, refererDomains, loginError, logout. Warning: redirects only work if neither the plugin nor the page it is displayed on are set to `hide at login`.'
    category: felogin
  felogin.redirectFirstMethod:
    default: false
    label: 'Use First Supported Mode from Selection'
    type: bool
    description: 'If set the first method from redirectMode which is possible will be used'
    category: felogin
  felogin.redirectPageLogin:
    default: 0
    label: 'After Successful Login Redirect to Page'
    type: int
    description: 'Page id to redirect to after Login'
    category: felogin
  felogin.redirectPageLoginError:
    default: 0
    label: 'After Failed Login Redirect to Page'
    type: int
    description: 'Page id to redirect to after Login Error'
    category: felogin
  felogin.redirectPageLogout:
    default: 0
    label: 'After Logout Redirect to Page'
    type: int
    description: 'Page id to redirect to after Logout'
    category: felogin
  felogin.redirectDisable:
    default: false
    label: 'Disable Redirect'
    type: bool
    description: 'If set redirecting is disabled'
    category: felogin
  felogin.forgotLinkHashValidTime:
    default: 12
    label: 'Time in hours how long the link for forgot password is valid'
    type: int
    description: 'How many hours the link for forgot password is valid'
    category: felogin
  felogin.domains:
    default: ''
    label: 'Allowed Referrer-Redirect-Domains'
    type: string
    description: 'Comma separated list of domains which are allowed for the referrer redirect mode'
    category: felogin
  felogin.exposeNonexistentUserInForgotPasswordDialog:
    default: false
    label: 'Expose existing users'
    type: bool
    description: 'Expose the information on whether or not the account for which a new password was requested exists. By default, that information is not disclosed for privacy reasons.'
    category: felogin
  felogin.view.templateRootPath:
    default: ''
    label: 'Path to template root (frontend)'
    type: string
    description: 'Path to template directory used for the plugin in the frontend. Extends the default template location.'
    category: felogin
  felogin.view.partialRootPath:
    default: ''
    label: 'Path to template partials (frontend)'
    type: string
    description: 'Path to partial directory for the plugin in the frontend. Extends the default partial location.'
    category: felogin
  felogin.view.layoutRootPath:
    default: ''
    label: 'Path to template layouts (frontend)'
    type: string
    description: 'Path to layout directory used for the plugin in the frontend. Can be used to introduce a custom layout.'
    category: felogin
