version: 1
name: typo3/styleguide
label: Styleguide Theme

dependencies:
  - typo3/fluid-styled-content
  # allow direct typoscript include (creates an implicit set)
  # left here on purpose to demonstrate usage of legacy extensions
  - TYPOSCRIPT:EXT:form/Configuration/TypoScript
  - TYPOSCRIPT:EXT:indexed_search/Configuration/TypoScript
  - typo3/felogin
  - typo3/seo-xml-sitemap
