version: 1
settings:
  styles.content.loginform.pid:
    default: '0'
    label: 'User Storage Page'
    type: string
    description: 'Define the Storage Folder with the Website User Records, using a comma separated list or single value'
  styles.content.loginform.recursive:
    default: '0'
    label: Recursive
    type: enum
    validators:
      -
        type: enum
        options:
          - '0'
          - '1'
          - '2'
          - '3'
          - '4'
          - '255'
    description: 'If set, also subfolder at configured recursive levels of the User Storage Page will be used'
  styles.content.loginform.showForgotPassword:
    default: false
    label: 'Display Password Recovery Link'
    type: boolean
    description: 'If set, the section in the template to display the link to the forgot password dialogue is visible.'
  styles.content.loginform.showPermaLogin:
    default: false
    label: 'Display Remember Login Option'
    type: boolean
    description: 'If set, the section in the template to display the option to remember the login (with a cookie) is visible.'
  styles.content.loginform.showLogoutFormAfterLogin:
    default: false
    label: 'Disable redirect after successful login, but display logout-form'
    type: boolean
    description: 'If set, the logout form will be displayed immediately after successful login.'
  styles.content.loginform.emailFrom:
    default: ''
    label: 'Email Sender Address'
    type: string
    description: 'email address used as sender of the change password emails'
  styles.content.loginform.emailFromName:
    default: ''
    label: 'Email Sender Name'
    type: string
    description: 'Name used as sender of the change password emails'
  styles.content.loginform.replyToEmail:
    default: ''
    label: 'Reply to email Address'
    type: string
    description: 'Reply to address used in the change password emails'
  styles.content.loginform.dateFormat:
    default: 'Y-m-d H:i'
    label: 'Date format'
    type: string
    description: 'Format for the link is valid until message (forgot password email)'
  styles.content.loginform.email.layoutRootPath:
    default: ''
    label: 'Layout root path'
    type: string
    description: 'Path to layout directory used for emails'
  styles.content.loginform.email.templateRootPath:
    default: 'EXT:felogin/Resources/Private/Email/Templates/'
    label: 'Template root path'
    type: string
    description: 'Path to template directory used for emails'
  styles.content.loginform.email.partialRootPath:
    default: ''
    label: 'Partial root path'
    type: string
    description: 'Path to partial directory used for emails'
  styles.content.loginform.email.templateName:
    default: PasswordRecovery
    label: 'Template name for emails. Plaintext emails get the .txt file extension.'
    type: string
    description: ''
  styles.content.loginform.redirectMode:
    default: ''
    label: 'Redirect Mode'
    type: string
    description: 'Comma separated list of redirect modes. Possible values: groupLogin, userLogin, login, getpost, referer, refererDomains, loginError, logout'
  styles.content.loginform.redirectFirstMethod:
    default: false
    label: 'Use First Supported Mode from Selection'
    type: boolean
    description: 'If set the first method from redirectMode which is possible will be used'
  styles.content.loginform.redirectPageLogin:
    default: 0
    label: 'After Successful Login Redirect to Page'
    type: int+
    description: 'Page id to redirect to after Login'
  styles.content.loginform.redirectPageLoginError:
    default: 0
    label: 'After Failed Login Redirect to Page'
    type: int+
    description: 'Page id to redirect to after Login Error'
  styles.content.loginform.redirectPageLogout:
    default: 0
    label: 'After Logout Redirect to Page'
    type: int+
    description: 'Page id to redirect to after Logout'
  styles.content.loginform.redirectDisable:
    default: false
    label: 'Disable Redirect'
    type: boolean
    description: 'If set redirecting is disabled'
  styles.content.loginform.forgotLinkHashValidTime:
    default: 12
    label: 'Time in hours how long the link for forgot password is valid'
    type: int+
    description: 'How many hours the link for forgot password is valid'
  styles.content.loginform.domains:
    default: ''
    label: 'Allowed Referrer-Redirect-Domains'
    type: string
    description: 'Comma separated list of domains which are allowed for the referrer redirect mode'
  styles.content.loginform.exposeNonexistentUserInForgotPasswordDialog:
    default: false
    label: 'Expose existing users'
    type: boolean
    description: 'Expose the information on whether or not the account for which a new password was requested exists. By default, that information is not disclosed for privacy reasons.'
  styles.content.defaultHeaderType:
    default: 2
    label: 'Default Header type'
    type: int
    description: 'Enter the number of the header layout to be used by default'
  styles.content.shortcut.tables:
    default: tt_content
    label: 'List of accepted tables'
    type: string
    description: ''
  styles.content.allowTags:
    default: 'a, abbr, acronym, address, article, aside, b, bdo, big, blockquote, br, caption, center, cite, code, col, colgroup, dd, del, dfn, dl, div, dt, em, figure, font, footer, header, h1, h2, h3, h4, h5, h6, hr, i, img, ins, kbd, label, li, link, meta, nav, ol, p, pre, q, s, samp, sdfield, section, small, span, strike, strong, style, sub, sup, table, thead, tbody, tfoot, td, th, tr, title, tt, u, ul, var'
    label: 'List of allowed HTML tags when rendering RTE content'
    type: string
    description: ''
  styles.content.image.lazyLoading:
    default: lazy
    label: 'Default settings for browser-native image lazy loading'
    type: enum
    validators:
      -
        type: enum
        options:
          - lazy
          - eager
          - auto
    description: 'Can be "lazy" (browsers could choose to load images later), "eager" (load images right away) or "auto" (browser will determine whether the image should be lazy loaded or not)'
  styles.content.image.imageDecoding:
    default: ''
    label: 'Default settings for an image decoding hint to the browser'
    type: enum
    validators:
      -
        type: enum
        options:
          - sync
          - async
          - auto
    description: 'Can be "sync" (synchronously for atomic presentation with other content), "async" (asynchronously to avoid delaying presentation of other content), "auto" (no preference in decoding mode) or an empty value to omit the usage of the decoding attribute (same as "auto")'
  styles.content.textmedia.maxW:
    default: 600
    label: 'Max Image/Media Width'
    type: int+
    description: 'This indicates that maximum number of pixels (width) a block of media elements inserted as content is allowed to consume'
  styles.content.textmedia.maxWInText:
    default: 300
    label: 'Max Image/Media Width (Text)'
    type: int+
    description: 'Same as above, but this is the maximum width when text is wrapped around an block of media elements. Default is 50% of the normal Max Media Item Width'
  styles.content.textmedia.columnSpacing:
    default: 10
    label: 'Advanced, Column space'
    type: int
    description: 'Horizontal distance between media elements in a block in content elements of type "Media & Images". If you change this manually in your CSS, you need to adjust this setting accordingly'
  styles.content.textmedia.rowSpacing:
    default: 10
    label: 'Advanced, Row space'
    type: int
    description: 'Vertical distance after each media elements row in content elements of type ""Text & Media". If you change this manually in your CSS, you need to adjust this setting accordingly'
  styles.content.textmedia.textMargin:
    default: 10
    label: 'Advanced, Margin to text'
    type: int
    description: 'Horizontal distance between an imageblock and text in content elements of type "Text & Images"'
  styles.content.textmedia.borderColor:
    default: '#000000'
    label: 'Media element border, color'
    type: color
    description: 'Bordercolor of media elements in content elements when "Border"-option for an element is set'
  styles.content.textmedia.borderWidth:
    default: 2
    label: 'Media element border, thickness'
    type: int
    description: 'Thickness of border around media elements in content elements when "Border"-option for element is set'
  styles.content.textmedia.borderPadding:
    default: 0
    label: 'Media element border, padding'
    type: int+
    description: 'Padding left and right to the media element, around the border'
  styles.content.textmedia.linkWrap.width:
    default: 800m
    label: 'Click-enlarge Media Width'
    type: string
    description: 'This specifies the width of the enlarged media element when click-enlarge is enabled'
  styles.content.textmedia.linkWrap.height:
    default: 600m
    label: 'Click-enlarge Media Height'
    type: string
    description: 'This specifies the height of the enlarged media element when click-enlarge is enabled'
  styles.content.textmedia.linkWrap.newWindow:
    default: false
    label: 'Advanced, New window'
    type: boolean
    description: "If set, every click-enlarged media element will open in it's own popup window and not the current popup window (which may have a wrong size for the media element to fit in)"
  styles.content.textmedia.linkWrap.lightboxEnabled:
    default: false
    label: 'Lightbox click-enlarge rendering'
    type: boolean
    description: 'Whether media elements with click-enlarge checked should be rendered lightbox-compliant'
  styles.content.textmedia.linkWrap.lightboxCssClass:
    default: lightbox
    label: 'Lightbox CSS class'
    type: string
    description: 'Which CSS class to use for lightbox links (only applicable if lightbox rendering is enabled)'
  styles.content.textmedia.linkWrap.lightboxRelAttribute:
    default: 'lightbox[{field:uid}]'
    label: 'Lightbox rel="" attribute'
    type: string
    description: 'Which rel="" attribute to use for lightbox links (only applicable if lightbox rendering is enabled)'
  styles.content.links.extTarget:
    default: _blank
    label: 'Target for external links'
    type: string
    description: ''
  styles.content.links.keep:
    default: path
    label: 'Parts to keep when building links'
    type: string
    description: 'Comma separated list of the link parts to show when building the link-text: scheme,path,query. Example: "" (empty) => www.example.com, "scheme,path" => http://www.example.com'
  styles.templates.templateRootPath:
    default: ''
    label: 'Path of Fluid Templates for all defined content elements'
    type: string
    description: ''
  styles.templates.partialRootPath:
    default: ''
    label: 'Path of Fluid Partials for all defined content elements'
    type: string
    description: ''
  styles.templates.layoutRootPath:
    default: ''
    label: 'Path of Fluid Layouts for all defined content elements'
    type: string
    description: ''
  plugin.tx_felogin_login.view.templateRootPath:
    default: ''
    label: 'Path to template root (FE)'
    type: string
    description: ''
  plugin.tx_felogin_login.view.partialRootPath:
    default: ''
    label: 'Path to template partials (FE)'
    type: string
    description: ''
  plugin.tx_felogin_login.view.layoutRootPath:
    default: ''
    label: 'Path to template layouts (FE)'
    type: string
    description: ''
  plugin.tx_indexedsearch.view.templateRootPath:
    default: 'EXT:indexed_search/Resources/Private/Templates/'
    label: 'Path to template root (FE)'
    type: string
    description: ''
  plugin.tx_indexedsearch.view.partialRootPath:
    default: 'EXT:indexed_search/Resources/Private/Partials/'
    label: 'Path to template partials (FE)'
    type: string
    description: ''
  plugin.tx_indexedsearch.view.layoutRootPath:
    default: 'EXT:indexed_search/Resources/Private/Layouts/'
    label: 'Path to template layouts (FE)'
    type: string
    description: ''
  plugin.tx_indexedsearch.settings.targetPid:
    default: 0
    label: 'Set the target page where search results are shown'
    type: int
    description: ''
  plugin.tx_indexedsearch.settings.rootPidList:
    default: ''
    label: 'A list of integer which should be root-pages to search from'
    type: string
    description: ''
  plugin.tx_seo.view.templateRootPath:
    default: 'EXT:seo/Resources/Private/Templates/'
    label: 'Path to template root (FE)'
    type: string
    description: ''
  plugin.tx_seo.view.partialRootPath:
    default: 'EXT:seo/Resources/Private/Partials/'
    label: 'Path to template partials (FE)'
    type: string
    description: ''
  plugin.tx_seo.view.layoutRootPath:
    default: 'EXT:seo/Resources/Private/Layouts/'
    label: 'Path to template layouts (FE)'
    type: string
    description: ''
  plugin.tx_seo.settings.xmlSitemap.sitemaps.pages.excludedDoktypes:
    default: '3, 4, 6, 7, 199, 254'
    label: 'Doktypes to exclude'
    type: string
    description: ''
  plugin.tx_seo.settings.xmlSitemap.sitemaps.pages.excludePagesRecursive:
    default: ''
    label: 'List of page uids which should be excluded recursive'
    type: string
    description: ''
  plugin.tx_seo.settings.xmlSitemap.sitemaps.pages.additionalWhere:
    default: "{#no_index} = 0 AND {#canonical_link} = ''"
    label: 'Additional where clause'
    type: string
    description: ''
  foo.bar:
    default: lol2
    label: 'lol title'
    type: string
    description: ''
