on:
  workflow_call:

jobs:
  cgl:
    name: 'CGL'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: .cache/composer
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-

      - name: Composer Install dependencies
        run: Build/Scripts/runTests.sh -s composerInstall -p ${{ matrix.php-version }}

      - name: CGL
        run: Build/Scripts/runTests.sh -s cglGit -n -p ${{ matrix.php-version }}

  composer_validate:
    name: 'Validate composer.json'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: composer validate
        run: Build/Scripts/runTests.sh -s composerValidate -p 7.4
