on:
  workflow_call:

jobs:
  cgl:
    name: 'CGL'
    runs-on: ubuntu-latest
      #container: fedora:38
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.2' ]

    steps:
#      - name: Configure sources
#        run: curl -fsSL "https://downloadcontentcdn.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/Release.key" | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg && echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://downloadcontentcdn.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /" | sudo tee /etc/apt/sources.list.d/podman_kubic.list
#
#      - name: Install xmllint
#        run: sudo apt-get install -y podman

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Composer Cache
        uses: actions/cache@v3
        with:
          path: .cache/composer
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-

      - name: Composer Install dependencies
        run: Build/Scripts/runTests.sh -s composerInstall -p ${{ matrix.php-version }}

      - name: CGL
        run: Build/Scripts/runTests.sh -s cglGit -n -p ${{ matrix.php-version }}

  composer_validate:
    name: 'Validate composer.json'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: composer validate
        run: Build/Scripts/runTests.sh -s composerValidate -p 8.2
